---
- name: test
  hosts: all
  gather_facts: no
  connection: local

  tasks:
    - name: Read file in hostname
      shell: bash /var/lib/awx/projects/log 
      register: hostname
      ignore_errors: True
