---
- name: test
  hosts: all
  gather_facts: no
  connection: local

  tasks:
    - name: Read file in hostname
      shell: bash /var/lib/awx/projects/_6__demo_project/awx.sh 
      register: hostname
      ignore_errors: True
