---
- name: EXOS Operation Box_Telnet
  hosts: all
  gather_facts: no

  tasks:
    - name: CLi show output(2)
      ios_command:
        commands:
          - show version
      register: show
